repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: debug-statements
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^tests/.*/fixtures/.*|.*\.excalidraw|.drawio.svg

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.166"
    hooks:
      - id: ruff

  - repo: https://github.com/dosisod/refurb
    rev: v1.8.0
    hooks:
      - id: refurb

  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.3.1"
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, "--ignore=E501,W503"]  # same as black

  # - repo: https://github.com/jazzband/pip-tools
  #   rev: 6.11.0
  #   hooks:
  #     - id: pip-compile
  #       files: ^requirements.in$
  #       args: ["--resolver=backtracking"]  # modern resolver
